version: '3.8'
services:
  app:
    container_name: go-simple-api
    build: .
    env_file:
      - .env.docker
    ports:
      - 5050:5050
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: db-simple-api
    env_file:
      - .env.docker
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./tables.sql:/docker-entrypoint-initdb.d/1-setup.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10